# 头部菜单，title: link
menu:
  搜索: /search
  全站导航: /nevigation
  喵语翻译器: /MLT
  归档: /archives
  分类: /categories
  标签: /tags
  关于我: /AboutMe

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /images/bg.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/nocover.jpg

# 首页自定义
index:
    # 开启后首页显示自定义标题，关闭后显示第一篇文章
    custom: true
    title: 坊洛酱的小作坊
    subtitle: '为什么不点一下右上角的菜单呢=￣ω￣='
    link: /nevigation


# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    twitter: https://twitter.com/Im_Fang_Luo
    github: https://github.com/rainbowbedrock
    email: mailto:rainbowbedrock@outlook.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '20e6dc2e92a82afbe6ef'
    # 应用秘钥
    clientSecret: 'c6a76478d328ef9379910c6dcc9a15efe0d02f61'
    # issue仓库名
    repo: 'rainbowbedrock.github.io'
    # Github名
    owner: 'rainbowbedrock'
    # Github名
    admin: ['rainbowbedrock']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: '坊洛'

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /images/favicon.png

# rss文件
rss: atom.xml

# manifest文件
manifest: /manifest.json